displayName=Nylo Freezer
author=PawgTank
description=Calculate the minimum Magic attack bonus needed to freeze Maiden nylocas at Theatre of Blood
tags=tob,theatre of blood,maiden,nylo,freeze,magic,calculator
version=1.0.0
plugins=com.nylofreezer.NyloFreezerPlugin
build=standard
